trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:

# Download the latest recommended NuGet exe

- task: NuGetToolInstaller@0
  displayName: "NuGet use 4.6.2"
  inputs:
    versionSpec: 4.6.2
- script: dotnet restore

# Build your .NET Core project (but avoid restore your packages again)

- task: DotNetCoreCLI@2
  displayName: ".NET build"
  inputs:
    projects: '**/*.csproj'
    arguments: --configuration $(BuildConfiguration) --no-restore

# Create the deployment package for your web project

- task: DotNetCoreCLI@2
  displayName: ".NET publish package"
  inputs:
    command: publish
    arguments: '--configuration $(BuildConfiguration) --no-restore --output $(Build.ArtifactStagingDirectory)/app/pkg'

# Publish your web project deployment packages as named artifact 'app'

- task: PublishBuildArtifacts@1
  displayName: "Publish artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
    ArtifactName: app
    publishLocation: Container
